cloth_store/urls.py
from django.contrib import admin
from django.template.defaulttags import url
from django.urls import path,include
from django.conf import settings
from django.conf.urls.static import static
from webstore import views
from django.contrib.auth import views as auth_views
from django.views.static import serve

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('product.urls')),
    path('login_user/', views.loginPage, name="login-user"),
    path('logout_user/', views.logoutUser, name="logout-user"),
    path('register_user/', views.register_customer, name="register-user"),
    path('register_brand/', views.register_brand, name="register-brand"),
    path('user_profile/', views.user_profile, name="user-profile"),
    path('password-change/', views.ChangePasswordView.as_view(), name='password-change'),
    path('password-reset/', auth_views.PasswordResetView.as_view(template_name='webstore/password_reset.html'), name='password_reset'),
    path('password-reset/done/', auth_views.PasswordResetView.as_view(template_name='webstore/password_reset_done.html'), name='password_reset_done'),
    path('password-reset-confirm/<uidb64>/<token>', auth_views.PasswordResetConfirmView.as_view(template_name='webstore/password_reset_confirm.html'), name='password_reset_confirm'),
    path('password-reset-complete/', auth_views.PasswordResetCompleteView.as_view(template_name='webstore/password_reset_complete.html'), name='password_reset_complete'),
]+ static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

product/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path('', views.Home.as_view(), name="home"),
    path('product_details/<int:pk>/', views.ProductDetails.as_view(), name="product_details"),
    path('product_sizes/', views.GetSize.as_view(), name="get_sizes"),
    path('product_details/<int:pk>/add_review/', views.ProductDetails.as_view(), name="add_review"),
    path('product_page/<str:category>/', views.ProductPage.as_view(), name="product_page"),
    path('target_audience/<str:target_audience>/', views.ProductPage.as_view(), name="target_audience"),
    path('cart/', views.ViewCart.as_view(), name="view_cart"),
    path('wishlist/', views.ViewWishlist.as_view(), name="view_wishlist"),
    path('add_to_cart/<int:product_id>/', views.AddToCart.as_view(), name="add_to_cart"),
    path('add_to_wish/<int:product_id>/', views.AddToWishlist.as_view(), name="add_to_wishlist"),
    path('remove_from_cart/<int:product_id>', views.RemoveFromCart, name="remove_from_cart"),
    path('remove_from_wishlist/<int:product_id>', views.RemoveFromWishlist, name="remove_from_wishlist"),
    path('confirm_order/', views.ConfirmOrder.as_view(), name="confirm_order"),
    path('cart/update', views.UpdateQuantity.as_view(), name="update_quantity"),
    path('faviorites/', views.FavioriteBrands.as_view(), name="faviorite_section"),
    path('searched_item/', views.SearchProduct.as_view(), name="searched_product"),
    path('filtered_item/', views.FilterProduct.as_view(), name="filter_product"),
    path('paymentHandler/', views.paymenthandler, name="PaytmentHandler"),
    path('view_orders/', views.ViewOrders.as_view(), name="ViewOrders"),
    path('view_order_details/<int:order_id>/', views.ViewOrderDetails.as_view(), name="ViewOrderDetails"),
    path('invoice/<str:order_id>/', views.GenerateInvoice.as_view(), name="GenerateInvoice"),
    path('invoice/<int:pid>/<str:purpose>', views.ReplaceReturn.as_view(), name="ReplaceReturn"),
    path('invoice/ReplaceReturnStatus/<int:pid>/<str:purpose>', views.ReplaceReturnStatus.as_view(), name="ReplaceReturnStatus"),
]

product/models.py
import datetime
from django.utils import timezone

from django.contrib import admin
from django.db import models
from webstore.models import User, Customer

size_choices = (
    ("XS", "XS"),
    ("S", "S"),
    ("M", "M"),
    ("L", "L"),
    ("XL", "XL"),
    ("XXL", "XXL"),
)

color_choice = (
    ("red", "red"),
    ("blue", "blue"),
    ("yellow", "yellow"),
    ("black", "black"),
)

gender_choice = (
    ("Men", "Men"),
    ("Women", "Women"),
    ("Kids", "Kids"))


# Create your models here.

class Colour(models.Model):
    colour = models.CharField(max_length=15)

class size(models.Model):
    size = models.CharField(max_length=10)


class Brand(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE)
    brand_name = models.CharField(max_length=30, unique=True)
    email = models.EmailField(max_length=50, unique=True)

    def __str__(self):
        return self.brand_name

class Category(models.Model):
    name = models.CharField(max_length=30, unique=True)
    def __str__(self):
        return self.name

class Product(models.Model):
    brand = models.ForeignKey(Brand, on_delete=models.CASCADE)
    category = models.ForeignKey(Category, on_delete=models.CASCADE)
    name = models.CharField(max_length=50)
    image = models.ImageField()
    short_line = models.CharField(max_length=40)
    price = models.FloatField()
    discount = models.IntegerField()
    target_audience = models.CharField(max_length=10, choices=gender_choice, default='Men')
    no_of_purchases = models.IntegerField(default=0)


    def discount_price(self):
        return "{:.2f}".format(self.price - ((self.price * self.discount)/100))

    def __str__(self):
        return self.name

class sub_products(models.Model):
    product = models.ForeignKey(Product, on_delete=models.CASCADE)
    quantity = models.IntegerField()
    size = models.CharField(max_length=10, choices=size_choices ,default='XL')
    color = models.CharField(max_length=10, choices=color_choice ,default='red')
    description = models.TextField()


class Reviews(models.Model):
    customer = models.ForeignKey(Customer, on_delete=models.CASCADE)
    product = models.ForeignKey(Product, on_delete=models.CASCADE)
    review = models.TextField()
    date_added = models.DateTimeField(auto_now_add=True)

class Cart(models.Model):
    customer = models.ForeignKey(Customer, on_delete=models.CASCADE)
    product = models.ForeignKey(sub_products, on_delete=models.CASCADE)
    added_quantity = models.IntegerField()

    @property
    def get_total(self):
        total = float(self.product.product.discount_price()) * self.added_quantity
        return total

class Order(models.Model):
    payment_status_choices = (
        ('SUCCESS', 'SUCCESS'),
        ('FAILURE', 'FAILURE'),
        ('PENDING', 'PENDING'),
    )

    customer = models.ForeignKey(Customer, on_delete=models.CASCADE)
    order_date = models.DateTimeField(auto_now_add=True)
    address = models.TextField()
    total_amount = models.FloatField()
    payment_method = models.CharField(max_length=30, default='Cash On Delivery')
    order_id = models.CharField(unique=True, max_length=100, null=True, blank=True, default=None)
    # related to razorpay
    razorpay_order_id = models.CharField(max_length=500, null=True, blank=True)
    razorpay_payment_id = models.CharField(max_length=500, null=True, blank=True)
    razorpay_signature = models.CharField(max_length=500, null=True, blank=True)
    payment_status = models.CharField(max_length=20, choices=payment_status_choices, default='PENDING')

    def __str__(self):
        return f"{self.id}     {self.customer.user}"

class Invoice(models.Model):
    status_choices = (
        ('Not Packed', 'Not Packed'),
        ('Ready For Shipment', 'Ready For Shipment'),
        ('Shipped', 'Shipped'),
        ('Delivered', 'Delivered')
    )
    status_refund = (
        ('Not Initiated', 'Not Initiated'),
        ('Initiated', 'Initiated'),
        ('Done', 'Done')
    )
    status_pickup = (
        ('Will Soon Pick Up the Product', 'Will Soon Pick Up the Product'),
        ('Pick Up Done', 'Pick Up Done')
    )

    # Order
    order = models.ForeignKey(Order, on_delete=models.CASCADE)
    product = models.ForeignKey(sub_products, on_delete=models.SET_DEFAULT, default=0)
    product_quantity = models.IntegerField()
    brand_name = models.CharField(max_length=50)
    product_name = models.CharField(max_length=50)
    buy_price = models.FloatField()
    product_discount = models.IntegerField()
    product_size = models.CharField(max_length=10)
    product_color = models.CharField(max_length=15)
    order_status = models.CharField(max_length=20, choices=status_choices, default='Not Packed')
    order_delivery_date = models.DateTimeField(blank=True, null=True)

    def return_available(self):
        return (self.order_delivery_date + datetime.timedelta(days=5)) > timezone.now()



    # returned Product
    returned_status = models.BooleanField(default=False)
    returned_date = models.DateTimeField(blank=True, null=True)
    returned_reason = models.TextField(blank=True)
    pick_up_date = models.DateTimeField(blank=True, null=True)
    pick_up_status = models.CharField(max_length=30, choices=status_pickup, default='Will Soon Pick Up the Product')
    refund_status = models.CharField(max_length=20, choices=status_refund, default='Not Initiated')


    # Replaced Product
    replaced_status = models.BooleanField(default=False)
    replaced_date = models.DateTimeField(blank=True, null=True)
    replacement_reason = models.TextField(blank=True)
    replace_pickup_date = models.DateTimeField(blank=True, null=True)
    replace_pickup_status = models.CharField(max_length=30, choices=status_pickup, default='Will Soon Pick Up the Product')
    replace_delivery_date = models.DateTimeField(blank=True, null=True)
    replace_delivery_status = models.CharField(max_length=20, choices=status_choices, default='Not Packed')
    replace_product_size = models.CharField(max_length=10, blank=True)
    replace_product_color = models.CharField(max_length=15, blank=True)


    def __str__(self):
        if self.order_status == 'Delivered':
            if self.returned_status:
                return f"{self.order}  ---  Requested for Return"
            elif self.replaced_status:
                if self.returned_status:
                    return f"{self.order}  ---  Requested for Replacement"
            else:
                return f"{self.order}  ---  Delivered"
        else:
            return f"{self.order}   ---  {self.order_status}"

class Favourites(models.Model):
    customer = models.ForeignKey(Customer, on_delete=models.CASCADE)
    brand = models.ForeignKey(Brand, on_delete=models.CASCADE)

class WishList(models.Model):
    customer = models.ForeignKey(Customer, on_delete=models.CASCADE)
    product = models.ForeignKey(Product, on_delete=models.CASCADE)

product/forms.py
from django.forms import  ModelForm
from .models import Order,Invoice

class confirm_order_form(ModelForm):
    class Meta:
        model = Order
        fields = ['address']

product/templates/product/base.html
{% load static %}

<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="UTF-8" />
    <meta http-equiv="X-UA-Compatible" content="IE=edge" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <link rel="shortcut icon" href="assets/favicon.ico" type="image/x-icon" />
    <!-- Bootstrap CSS -->
    <link href="https://stackpath.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css" rel="stylesheet" type="text/css">
    <link rel="stylesheet" href="{% static 'style/base.css' %}" />
    <link
      href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.min.css"
      rel="stylesheet"
      integrity="sha384-EVSTQN3/azprG1Anm3QDgpJLIm9Nao0Yz1ztcQTwFspd3yD65VohhpuuCOmLASjC"
      crossorigin="anonymous"
    />
      <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.11.2/css/all.css" />
    <link rel="preconnect" href="https://fonts.googleapis.com">
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
    <link href="https://fonts.googleapis.com/css2?family=Dancing+Script:wght@700&family=Lobster&display=swap" rel="stylesheet">
    <title>ClothFlossy.com</title>
    <script src="https://code.jquery.com/jquery-3.6.0.min.js" integrity="sha256-/xUj+3OJU5yExlq6GSYGSHk7tPXikynS7ogEvDej/m4=" crossorigin="anonymous"></script>
      <script src="https://cdnjs.cloudflare.com/ajax/libs/jquery/3.3.1/jquery.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.9/umd/popper.min.js"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js"></script>
  </head>

  <body>
    {% include 'product/navbar.html' %}
    {% if messages %} 
    {% for message in messages %}
    <div class="container p-0">
      <div class="alert {{ message.tags }} alert-dismissible" role="alert" id="msg">
        {{ message }}
        <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close" ></button>
      </div>
    </div>
    {% endfor %}
    {% endif %}
    {% block content %} 
    {% endblock %}

    <script
      src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/js/bootstrap.bundle.min.js"
      integrity="sha384-MrcW6ZMFYlzcLA8Nl+NtUVF0sA7MsXsP1UyJoMp4YLEuNSfAP+JcXn/tWtIaxVXM"
      crossorigin="anonymous"></script>
  </body>
</html>

product/templates/product/confirm_order.html
{% extends 'product/base.html' %}
{% load static %}
{% block content %}

<section class="h-100 h-custom" style="background-color: #eee;">
  <div class="container py-5 h-100">
    <div class="row d-flex justify-content-center align-items-center h-100">
      <div class="col">
        <div class="card">
          <div class="card-body p-4">
            <div class="row">
              <div class="col-lg-7">
                <h5 class="mb-3"><a href="{% url 'home' %}" class="text-body"><i
                      class="fas fa-long-arrow-alt-left me-2"></i>Continue shopping</a></h5>
                <hr>
                <div class="d-flex justify-content-between align-items-center mb-4">
                  <div>
                    <p class="mb-1">Order Summary</p>
                  </div>
                </div>
{#                  Products#}
                  {% for item in products %}

                    <div class="card mb-3">
                  <div class="card-body">
                    <div class="d-flex justify-content-between">
                      <div class="d-flex flex-row align-items-center">
                        <div>
                          <img
                            src="{{ item.product.product.image.url }}"
                            class="img-fluid rounded-3" alt="Shopping item" style="width: 65px;">
                        </div>
                        <div class="ms-3">
                          <h5>{{ item.product.product.name }}</h5>
                          <p class="small mb-0">{{ item.product.product.short_line }}</p>
                        </div>
                      </div>
                      <div class="d-flex flex-row align-items-center">
                        <div style="width: 200px;">
                          <h5 class="fw-normal mb-0">Price: {{ item.product.product.discount_price}}</h5>
                        </div>
                        <div style="width: 50px;">
                          <h5 class="fw-normal mb-0">{{ item.added_quantity }}</h5>
                        </div>
                        <div style="width: 100px;">
                            <h5>Rs. <span class="mb-0" id="p_price{{ forloop.counter }}">{{ item.get_total }}</span></h5>
                        </div>
                      </div>
                    </div>
                  </div>
                </div>
                  {% endfor %}
              </div>
              <div class="col-lg-5">

                <div class="card bg-primary text-white rounded-3">
                  <div class="card-body">
                    <div class="d-flex justify-content-between align-items-center mb-4">
                      <h5 class="mb-0">Order Details</h5>
                    </div>

                    <form class="mt-4" method="POST">
                        {% csrf_token %}
                      <div class="form-outline form-white mb-4">
                        <label class="form-label">Shipping Address</label>
                        {{ form.address }}
                      </div>
                        <hr class="my-4">

                    <div class="d-flex justify-content-between">
                      <p class="mb-2">Subtotal</p>
                      <span class="mb-2"><input name="total_amount" type="text" id="sub_total" class="form-control" style="background: transparent; color: white;text-align: end; border: none; margin-left: 12px;"/></span>
                    </div>

                    <div class="d-flex justify-content-between">
                      <p class="mb-2">Shipping</p>
                      <p style="margin-left:330px;">Rs. </p><span class="mb-2" id="shipping_tax">20.00</span>
                    </div>

                    <div class="d-flex justify-content-between mb-4">
                      <p class="mb-2">Total(Incl. taxes)</p>
                      <span style="margin-left:245px;">Rs. </span><span class="mb-2" id="sub_total1"></span>
                    </div>

                    <button type="submit" class="btn btn-info btn-block btn-primary" name="COD">
                        <span>Rs. </span><span id="sub_total2"></span>
                        <span style="margin-left: 20px">COD</span>
                    </button>

                    <button type="submit" class="btn btn-info btn-block btn-primary" name="Rozerpay">
                        <span>Rs. </span><span id="sub_total3"></span>
                        <span style="margin-left: 20px">Razorpay</span>
                    </button>
                    </form>

                  </div>
                </div>

              </div>

            </div>

          </div>
        </div>
      </div>
    </div>
  </div>
</section>
<footer></footer>
<script>
    var i = 0
    var total_amount = 0
    while (true) {
        i+=1
        var price = 'p_price'+i
        if (document.getElementById(price)){
            total_amount += parseFloat((document.getElementById(price).innerHTML))
        }else{
            break
        }
    }

    if (total_amount<500){
      document.getElementById('shipping_tax').innerText = 50
    }else{
      document.getElementById('shipping_tax').innerText = 0}

    var tax = parseFloat(document.getElementById('shipping_tax').innerText)

    document.getElementById('sub_total').value = total_amount.toFixed(2)
    document.getElementById('sub_total1').innerText = (total_amount + tax).toFixed(2)
    document.getElementById('sub_total2').innerText = (total_amount + tax).toFixed(2)
    document.getElementById('sub_total3').innerText = (total_amount + tax).toFixed(2)

</script>
<script src="{% static 'js/footer.js' %}"></script>
{% endblock content %}

product/templates/product/filter_items_page.html
{% extends 'product/base.html' %}
{% load static %}

{% block content %}

<section class="search-results">
    <h2 class="heading">search results for <span>product</span></h2>
    <div class="product-container-filter">
        {% for product in products %}
            <div class="product-card">
                <div class="product-image">
                    <span class="discount-tag">{{ product.discount }}% off</span>
                    <a href="{% url 'product_details' product.id %}"><img src="{{ product.image.url }}" class="product-thumb" alt=""></a>
                    <a href="{% url 'add_to_wishlist' product.id %}"><button class="card-btn">add to WishList</button></a>
                </div>
                <div class="product-info">
                    <h2 class="product-brand">{{ product.brand }}</h2>
                    <h5 class="product-brand">{{ product.name }}</h5>
                    <p class="product-short-des">{{ product.short_line }}</p>
                    {% if product.discount > 0 %}
                        <span class="price" >Rs. {{ product.discount_price }}</span><span class="actual-price">Rs. {{ product.price }}</span>
                    {% else %}
                        <span class="price">Rs. {{ product.price }}</span>
                    {% endif %}
                </div>
            </div>
        {% endfor %}
    </div>
</section>

<footer></footer>
<script src="{% static 'js/footer.js' %}"></script>
{% endblock content %}

product/templates/product/invoice.html
<!DOCTYPE html>
<html lang="en">
{% load static %}
<head>
  <title>Invoice Cloth-Flossy</title>
<style>
  .clearfix:after {
  content: "";
  display: table;
  clear: both;
}

a {
  text-decoration: underline;
}

body {
  position: relative;
  margin: 0 auto;
  color: #001028;
  background: #FFFFFF;
  font-family: Arial, sans-serif;
  font-size: 14px;
  font-family: Arial;
}

header {
  padding: 10px 0;
  margin-bottom: 30px;
}

#logo {
  text-align: center;
  margin-bottom: 10px;
}

#logo img {
  width: 90px;
}

h1 {

  color: #5D6975;
  font-size: 2.4em;
  line-height: 1.4em;
  font-weight: normal;
  text-align: center;
  margin: 0 0 20px 0;
}

#project {
  float: left;
}

#project span {
  color: #5D6975;
  text-align: right;
  width: 52px;
  margin-right: 10px;
  display: inline-block;
  font-size: 14px;
}

#company {
  float: right;
  text-align: right;
}

#project div,
#company div {
  white-space: nowrap;
}

table {
  width: 100%;
  border-collapse: collapse;
  border-spacing: 0;
  margin-bottom: 20px;
}



table th,
table td {
  text-align: center;
}

table th {


  color: #5D6975;
  border-bottom: 1px solid #C1CED9;
  white-space: nowrap;
  font-weight: normal;
}

table .service,
table .desc {
  text-align: left;
}

table td {
 padding-top:5px;
 padding-bottom:5px;

}

table tr {
  border-bottom: 1px solid #C1CED9;
}

table td.service,
table td.desc {
  vertical-align: top;
}

table td.unit,
table td.qty,
table td.total {
  font-size: 1.2em;
}

table td.grand {
  border-top: 1px solid #5D6975;;
}

#notices .notice {
  color: #5D6975;
  font-size: 1.2em;
}

footer {
  color: #5D6975;
  width: 100%;
  height: 30px;
  position: absolute;
  bottom: 0;
  border-top: 1px solid #C1CED9;
  padding: 8px 0;
  text-align: center;
}


  </style>
</head>

<body>
  <header class="clearfix">
    <div id="logo" style="display:flex; justify-content:center; align-items:center;">
      <h1 class="brand-name">Cloth-Flossy</h1>
    </div>
    <h1>INVOICE</h1>
    <div id="company" class="clearfix">
      <div>Cloth-Flossy</div>
      <div><a href="mailto:company@example.com">ClothFlossy@gmail.com</a></div>
      <div><a href="https://cloth-flossy.herokuapp.com/">https://cloth-flossy.herokuapp.com/</a></div>
    </div>
    <div id="project">
      <div><span>CLIENT:</span> {{name}} </div>
      <div><span>EMAIL:</span> <a href="mailto:{{user_email}}">{{user_email}}</a></div>
      <div><span>DATE:</span> {{date}}</div>
      <div><span>INVOICE ID:</span> {{order_id}}</div>
      <div><span>TRANSACTION ID:</span> {{transaction_id}}</div>
    </div>
    <br>
    <br>
  </header>
    <div class="table-container" style="overflow-x:auto">
      <table class="table" style="width:100%">
          <thead>
              <tr>
                  <th scope="col">PRODUCT</th>
                  <th scope="col">QUANTITY</th>
                  <th scope="col">PRICE</th>
                  <th scope="col">COLOR</th>
                  <th scope="col">SIZE</th>
              </tr>
          </thead>
          <tbody>
              {% for i in order.invoice_set.all %}
              <tr>
                  <td scope="row">{{i.product.product.name}}</td>
                  <td>{{i.product_quantity}}</td>
                  <td>{{i.buy_price}}</td>
                  <td>{{i.product_color}}</td>
                  <td>{{i.product_size}}</td>
              </tr>
              {% endfor %}
              <tr>
                  <td scope="row"></td>
                  <td>TOTAL: </td>
                  <td>{{ amount }}</td>
              </tr>
          </tbody>
      </table>

    </div>
    <p style="text-align:right; font-size:12px;">*All values are in INR<p>
</body>

</html>

product/templates/product/order_history.html
{% extends 'product/base.html' %}
{% load static %}
{% block content %}

<section class="h-100 gradient-custom">
    <div class="container-fluid py-5 h-100">
        <div class="row d-flex justify-content-center align-items-center h-100">
            <div class="col-lg-10 col-xl-8">
                <div class="card" style="border-radius: 10px;">
                    <div class="card-header px-4 py-5">
                        <h5 class="text-muted mb-0">Thanks for your Orders, <span style="color: #a8729a;">{{ orders.first.customer.name }}</span>!</h5>
                    </div>
                    <div class="card-body p-4">
                        <div class="d-flex justify-content-between align-items-center mb-4">
                            <p class="lead fw-normal mb-0" style="color: #a8729a;"> Your Orders :: </p>
                        </div>
                        <div class="card shadow-0 border mb-4">
                            <div class="card-body">
                                <div class="row">
                                    <div class="col-md-2 text-center d-flex justify-content-center align-items-center">
                                        <p class="text-muted mb-0 small"><strong>Order Id</strong></p>
                                    </div>
                                    <div class="col-md-2 text-center d-flex justify-content-center align-items-center">
                                        <p class="text-muted mb-0">Order Date</p>
                                    </div>
                                    <div class="col-md-2 text-center d-flex justify-content-center align-items-center">
                                        <p class="text-muted mb-0 small">Payment Method</p>
                                    </div>
                                    <div class="col-md-2 text-center d-flex justify-content-center align-items-center">
                                        <p class="text-muted mb-0 small">Payment Status</p>
                                    </div>
                                    <div class="col-md-1 text-center d-flex justify-content-center align-items-center">
                                        <p class="text-muted mb-0 small">Total Items</p>
                                    </div>
                                    <div class="col-md-2 text-center d-flex justify-content-center align-items-center">
                                        <p class="text-muted mb-0 small">Total Amount</p>
                                    </div>
                                </div>
                            </div>
                        </div>

                        {% for order in orders %}
                        <div class="card shadow-0 border mb-4">
                            <div class="card-body">
                                <div class="row">
                                    <div class="col-md-2 text-center d-flex justify-content-center align-items-center">
                                        <p class="text-muted mb-0 small"><strong>{{ order.order_id }}</strong></p>
                                    </div>
                                    <div class="col-md-2 text-center d-flex justify-content-center align-items-center">
                                        <p class="text-muted mb-0">{{ order.order_date }}</p>
                                    </div>
                                    <div class="col-md-2 text-center d-flex justify-content-center align-items-center">
                                        <p class="text-muted mb-0 small">{{ order.payment_method }}</p>
                                    </div>
                                    <div class="col-md-2 text-center d-flex justify-content-center align-items-center">
                                        <p class="text-muted mb-0 small">{{ order.payment_status }}</p>
                                    </div>
                                    <div class="col-md-1 text-center d-flex justify-content-center align-items-center">
                                        <p class="text-muted mb-0 small">{{ order.invoice_set.all|length }}</p>
                                    </div>
                                    <div class="col-md-2 text-center d-flex justify-content-center align-items-center">
                                        <p class="text-muted mb-0 small">{{ order.total_amount }}</p>
                                    </div>
                                    <div class="col-md-1 text-center d-flex justify-content-center align-items-center">
                                        <a href="{% url 'ViewOrderDetails' order.id %}"><p class="text-muted mb-0 small">More Details</p></a>
                                    </div>
                                </div>
                            </div>
                        </div>
                        {% endfor %}

                    </div>
                </div>
            </div>
        </div>
    </div>
</section>

{% endblock content %}

product/templates/product/replace.html
{% extends 'product/base.html' %}
{% load static %}
{% block content %}

<section class="container" style="margin-top:200px;">S
  <form method="POST">
    {% csrf_token %}
    <div class="form-outline">
      <label class="form-label" for="textAreaExample"> Why You Want to Replace/Return the Product  ??? </label>
      <textarea class="form-control" id="textAreaExample" rows="4" placeholder="Share Your Review Here ..." name="return_tab"></textarea>
    </div>

    <p class="product-sub-heading" style="margin-top: 25px; ">select Color</p>
    <select class="form-select" aria-label="Default select example" style="width: 400px;" name="color_dropdown"
            id="color_drop_down">
        <option selected>Chose Color</option>
        {% for i in product.sub_products_set.all %}
        {% ifchanged %}<option>{{ i.color }}</option>{% endifchanged %}
        {% endfor %}
    </select>

    <p class="product-sub-heading">select size</p>
    <select class="form-select" aria-label="Default select" style="width: 400px;" name="size_dropdown"
            id="size_drop_down">
        <option id="XS" disabled>XS</option>
        <option id="S" disabled>S</option>
        <option id="M" disabled>M</option>
        <option id="L" disabled>L</option>
        <option id="XL" disabled>XL</option>
        <option id="XXL" disabled>XXL</option>
    </select>

    <button class="btn btn-primary" type="submit">submit</button>
  </form>
</section>

<script>
$("#color_drop_down").change(function (e) {
        e.preventDefault();
        var color = $(this).val()
        var p_id = {{ product.id }}
        // GET AJAX request
        $.ajax({
            type: 'GET',
            url: "{% url 'get_sizes' %}",
            data: {'color':color, 'p_id':p_id},
            success: function (response) {
                    $('#size_drop_down').empty()
                    $('#size_drop_down').append('<option id="XS" disabled>XS</option> <option id="S" disabled>S</option> <option id="M" disabled>M</option> <option id="L" disabled>L</option> <option id="XL" disabled>XL</option> <option id="XXL" disabled>XXL</option>')
                    $.each(response.color_wise_size, function(key, value) {
                        document.getElementById(value['size']).disabled = false;
})
                }
        })
});
</script>
{% endblock content %}